import React, { useContext, useEffect, useState } from "react";
import { Container, Row, Col } from "react-bootstrap";
import styles from "../../styles/Home.module.css";
import queryString from "query-string";
import { Table } from "react-bootstrap";
import Head from "next/head";
import { Form } from "react-bootstrap";
import { StudentContext } from "../../context/StudentContext";

function student() {
  const [student, setStudent] = useState();
  // const [studentDetails, setSetudentDetails] = useState();
  const [id, setId] = useState();
  const { updateStudent, fetchSingleStudentDetails, studentDetails } =
    useContext(StudentContext);
  useEffect(() => {
    const value = queryString.parse(window.location.search);
    setStudent(JSON.parse(value.data));
    setId(JSON.parse(value.data).reg_no);
    const d = fetchSingleStudentDetails(JSON.parse(value.data).reg_no);
  }, []);
  console.log(studentDetails);

  const [name, setName] = useState();
  const [email, setEmail] = useState();
  const [mobile, setMobile] = useState();
  const [iwt, setIwt] = useState();
  const [mcs, setMcs] = useState();
  const [bigData, setBigdata] = useState();
  const [ml, setMl] = useState();

  const handleName = (e) => {
    setName(e.target.value);
  };
  const handleEmail = (e) => {
    setEmail(e.target.value);
  };
  const handleMobile = (e) => {
    setMobile(e.target.value);
  };
  const handleIwt = (e) => {
    setIwt(e.target.value);
  };
  const handleMcs = (e) => {
    setMcs(e.target.value);
  };
  const hnadleBigdata = (e) => {
    setBigdata(e.target.value);
  };
  const handleMl = (e) => {
    setMl(e.target.value);
  };

  const handleSubmit = () => {
    updateStudent({ name, email, mobile, iwt, mcs, bigData, ml, id });
  };

  return (
    <>
      <Head>
        <title>IWT Assignment - Attendance System</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://www.w3schools.com/w3css/4/w3.css"
        />
      </Head>
      {student && (
        <Row>
          <Col xs={12}>
            <div className={styles.textContainer}>
              <h1>{student.name}</h1>
              <div>
                <h4>Reg No : {student.reg_no}</h4>
                <h4>Mobile No : {student.mobile}</h4>
                <h4>Institutional Email : {student.in_email}</h4>
                <h4>Email : {student.email}</h4>
              </div>
            </div>
          </Col>
        </Row>
      )}
      <div className={styles.form}>
        <h4>EDIT DETAILS</h4>
        <Row>
          <Col xs="6">
            <Form.Group className="mb-3" controlId="formBasicEmail">
              <Form.Control
                type="name"
                placeholder="Enter name"
                onChange={handleName}
              />
            </Form.Group>
          </Col>
          <Col xs="6">
            <Form.Group className="mb-3" controlId="formBasicEmail">
              <Form.Control
                type="email"
                placeholder="Enter personal email"
                onChange={handleEmail}
              />
            </Form.Group>
          </Col>
          <Col xs="6">
            <Form.Group className="mb-3" controlId="formBasicEmail">
              <Form.Control
                type="mobile"
                placeholder="Enter mobile number"
                onChange={handleMobile}
              />
            </Form.Group>
          </Col>
          <Col xs="6">
            <Form.Group className="mb-3" controlId="formBasicEmail">
              <Form.Control
                type="number"
                placeholder="Enter attendance (IWT)"
                onChange={handleIwt}
              />
            </Form.Group>
          </Col>
          <Col xs="6">
            <Form.Group className="mb-3" controlId="formBasicEmail">
              <Form.Control
                type="number"
                placeholder="Enter attendance (MCS)"
                onChange={handleMcs}
              />
            </Form.Group>
          </Col>
          <Col xs="6">
            <Form.Group className="mb-3" controlId="formBasicEmail">
              <Form.Control
                type="number"
                placeholder="Enter attendance (Big Data)"
                onChange={hnadleBigdata}
              />
            </Form.Group>
          </Col>
          <Col xs="6">
            <Form.Group className="mb-3" controlId="formBasicEmail">
              <Form.Control
                type="number"
                placeholder="Enter attendance (ML)"
                onChange={handleMl}
              />
            </Form.Group>
          </Col>
          <Col xs="6">
            <button className="btn btn-primary" onClick={handleSubmit}>
              Submit
            </button>
          </Col>
        </Row>
      </div>

      <div className={styles.sem}>
        <h4>ATTENDANCE</h4>
        <br />
        <Table striped bordered hover>
          <thead>
            <tr>
              <th>IWT</th>
              <th>MCS</th>
              <th>BIG DATA</th>
              <th>ML</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{studentDetails && studentDetails[0].iwt}</td>
              <td>{studentDetails && studentDetails[0].mcs}</td>
              <td>{studentDetails && studentDetails[0].big_data}</td>
              <td>{studentDetails && studentDetails[0].ML}</td>
            </tr>
          </tbody>
        </Table>
      </div>
      <footer className={styles.footer}>
        Student Attendance - Developed By Jeet
        <script
          src="https://unpkg.com/react/umd/react.production.min.js"
          crossOrigin="anonymous"
        ></script>
        <script
          src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"
          crossOrigin="anonymous"
        ></script>
        <script
          src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js"
          crossOrigin="anonymous"
        ></script>
      </footer>
    </>
  );
}

export default student;
